---
notifications:
  email: false
language: ruby
rvm:
  - 1.9.3
  - 2.1.0
  - 2.3.0
  - 2.5.0
cache: bundler
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.8.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.0.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.1.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.3.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.5.0" STRICT_VARIABLES=yes

matrix:
  fast_finish: true
  exclude:
  # exclude incompatible versions
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 5.0.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 5.1.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 5.2.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 5.3.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 5.5.0" STRICT_VARIABLES=yes

  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 5.0.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 5.1.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 5.2.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 5.3.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 5.5.0" STRICT_VARIABLES=yes